### ISSUE TITLE
Make it easier for the users to find what went wrong when a task failed

### ISSUE THREAD

**Issue by anandology** [pipalacademy/rajdhani-challenge#8]
Right now we just say if a task is successful or failed. We need to way to tell them what went wrong when a task fails. 

## Checks

Make a task have multiple checks and show the status of each check to the user, including the successful ones. 

The output of each task would look like:

```
PASS Test autocomplete for "sbc"
PASS Test autocomplete for "bangal"
PASS Test autocomplete for "guntur"
FAIL Test autocomplete for "chennai"
    Expected 7 stations: MS, MSC, MAS, MPKT, MPK, MSF, MSB
    Found only 5: MS, MSC, MAS, MPKT, MPK
```

Or a request to the user site might have failed.

```
ERROR Test autocomplete for "chennai"
   A request to https://anandology.com/api/stations?q=chennai failed with an internal error.
```

This information should be stored in the db to be able to show it to the users. 

## Code Changes

To make this work, we need to have an abstraction for checks. Each check would be a class and that would return a human readable error message when the check fails.

Each task could be a class with checks.

```
@task("autocomplete")
class TaskAutocomplete:
    """Implement the autocomplete on the home page.

    The autocomplete on the home page to select the from and to stations is
    a dummy implementation. Replace that with a correct implementation.
    """
    checks = [
        CheckAutocomplete("sbc", ["SBC"]),
        CheckAutocomplete("bangal", ["SBC", "BNCE", "BNC", "BJY"]
    ]
```

Or should we switch to yaml for specifying tasks?

```
tasks:
  - name: homepage
     title: Enable the homepage
     description: |
        Set `enable_homepage = True` in the `rajdhani/config.py`.
     checks:
         - check_flag:
              flag: "homepage"
  - name: autocomplete
     title: Implement the autocomplete on the home page.
     description: |
         The autocomplete on the home page to select the from and to stations is
         a dummy implementation. Replace that with a correct implementation.
     checks:
         - check_autocomplete:
              q: "sbc"
              expected_stations: SBC
```

Or create one file for task as markdown with yaml header.

```
title: Implement the autocomplete on the home page.
checks:
- check_autocomplete:
    q: sbc
    expected_stations: 
      - SBC
- check_autocomplete:
    q: bengal
    expected_stations: 
      - SBC
      - BNCE
      - BNC
      - BJY
---
The autocomplete on the home page to select the from and to stations is
a dummy implementation. Replace that with a correct implementation.
```

**Comment by anandology** [comment]
@nikochiko what do you think?

**Comment by nikochiko** [comment]
This would be very helpful!
I think all three are good ways to do it.
YAML/YAML-in-markdown are less verbose, but the tests most likely won't need too many changes once defined.

**Comment by anandology** [comment]
I'm envisioning a product where people can create new challenges directly from the UI. They can specify each task by writing the title and description and specifying the checks. 

Custom checks can be added by specifying an API endpoint. 

For example in case of rajdhani-challenge, we'll have to deploy check_autocomplete and check_flag as an API (possibly on hamr). 

But for now, I think I'll go with one single yaml file.

**Comment by anandology** [comment]
Settled with this format. 

```yaml
name: homepage
title: Enable the homepage.
description: |
  Set `enable_homepage = True` in the `rajdhani/config.py`.
checks:
  - webpage_content:
      url: /
      has_text: "<h2>Search Trains</h2>"
---
name: autocomplete
title: Implement the autocomplete on the home page.
description: |
  The autocomplete on the home page to select the from and to stations is
  a dummy implementation. Replace that with a correct implementation.
checks:
  - check_autocomplete:
      q: sbc
      result:
        - SBC
  - check_autocomplete:
      q: bengal
      result:
        - SBC
        - BNCE
        - BNC
        - BJY
```

@nikochiko
